Gdp/add push campaigns
lafranceinsoumise/nuntius pull request #12
Opened 2021-11-09 14:42 UTC by giuseppedeponte

2021-11-15 15:04 UTC, jillro commented on nuntius/utils/notifications.py
> +    )
Pourquoi rajouter utm_content et utm_term ici ?

2021-11-15 15:04 UTC, jillro commented on pyproject.toml
> +apns = "^2.0.1"
est-ce qu'il faut pas les mettre en optional comme django-anymail ?

2021-11-15 15:28 UTC, giuseppedeponte commented on README.md
> +        and `django-push-notifications.GCMDevice` model instances
Le nom du modèle est toujours `GCMDevice`, même si on utilise FCM - ce seront les paramètres de configuration qui seront différents

2021-11-15 15:31 UTC, giuseppedeponte commented on nuntius/utils/notifications.py
> +    )
Vu que le clic sur la notification ouvre un lien j'ai gardé les mêmes informations que pour les liens d'e-mail. Tu penses qu'il n'y en aura pas besoin pour les notifications ?

2021-11-15 15:40 UTC, jillro commented on nuntius/utils/notifications.py
> +    )
Dans les mails on rajoute effectivement utm_term à la génération parce qu'on peut pas le rajouter à la redirection (le segment lié à la campagne peut avoir changé entre deux). Effectivement c'est la même situation pour les campagnes push. Par contre pour utm_content ça n'est pas le cas, et je dirais même que s'il a tout le temps la même valeur, autant l’omettre carrément.

2021-11-15 15:41 UTC, giuseppedeponte commented on nuntius/utils/notifications.py
> +    )
Ok, je vais l'enlever alors

2021-11-16 10:50 UTC, jillro approved these changes

2021-11-16 10:50 UTC, jillro commented
@aktiur tu peux review aussi ?

2021-11-30 14:31 UTC, aktiur requested changes
Il y a un truc qui manque avant mise en prod, et un refactoring à mon avis nécessaire à moyen terme.

Je ne vois pas de gestion des retry sur l'envoi des notifications push (à moins que ce ne soit géré directement par les bibliothèques sous-jacentes ?). Du coup au moindre problème passager, on va enchaîner les erreurs d'envoi de push très rapidement et marquer plein de personnes en erreur, alors qu'il n'y a pas de problème sous-jacent. Voir par exemple ce que j'ai fait sur le `ConnectionManager` pour la gestion de la connexion SMTP et de l'envoi, dans `nuntius/management/commands/nuntius_worker.py`.

Sur la question de plus long terme, la duplication de code qu'entraîne le dédoublement des processes du worker entre email d'un côté et push de l'autre m'embête, un peu parce que ça permet moins de contrôler l'usage (qui sera double si on envoie des campagnes mails et push en même temps), mais surtout parce que ça dégrade à mon avis la maintenabilité.

En effet tout le code lié à la synchronisation entre les processes est dupliqué entre les deux fonctions de gestion des emails et celles de gestion des push, et toute évolution ou correction de l'un doit corriger exactement pareil l'autre, ce qui est généralement très pète-geule. Rien que là c'est pas évident de vérifier que les deux fonctions font bien exactement la même chose.

Il vaudrait mieux refactorer pour avoir un unique type de process de gestion de campagne, et un unique type de process d'envoi, et qu'ils soient capables de gérer polymorphiquement aussi bien des campagnes mail que push.

2021-12-01 11:43 UTC, giuseppedeponte commented
> Il y a un truc qui manque avant mise en prod, et un refactoring à mon avis nécessaire à moyen terme.
> 
> Je ne vois pas de gestion des retry sur l'envoi des notifications push (à moins que ce ne soit géré directement par les bibliothèques sous-jacentes ?). Du coup au moindre problème passager, on va enchaîner les erreurs d'envoi de push très rapidement et marquer plein de personnes en erreur, alors qu'il n'y a pas de problème sous-jacent. Voir par exemple ce que j'ai fait sur le `ConnectionManager` pour la gestion de la connexion SMTP et de l'envoi, dans `nuntius/management/commands/nuntius_worker.py`.
> 
> Sur la question de plus long terme, la duplication de code qu'entraîne le dédoublement des processes du worker entre email d'un côté et push de l'autre m'embête, un peu parce que ça permet moins de contrôler l'usage (qui sera double si on envoie des campagnes mails et push en même temps), mais surtout parce que ça dégrade à mon avis la maintenabilité.
> 
> En effet tout le code lié à la synchronisation entre les processes est dupliqué entre les deux fonctions de gestion des emails et celles de gestion des push, et toute évolution ou correction de l'un doit corriger exactement pareil l'autre, ce qui est généralement très pète-geule. Rien que là c'est pas évident de vérifier que les deux fonctions font bien exactement la même chose.
> 
> Il vaudrait mieux refactorer pour avoir un unique type de process de gestion de campagne, et un unique type de process d'envoi, et qu'ils soient capables de gérer polymorphiquement aussi bien des campagnes mail que push.

J'ai essayé d'ajouter la gestion des _retries_ pour les notifications push en m'inspirant de ce qui était fait pour les emails.
Sinon j'avais essayé de dupliquer le moins de code possible dans les processes du worker, mais dupliquer tout de même les parties qui me semblaient assez différentes pour éviter de casser l'envoi d'e-mail et pour permettre aux deux fonctionnalités d'évoluer en parallèle si besoin à l'avenir. Mais on pourra effectivement à moyen terme mieux factoriser pour réduire encore plus la duplication de code.

2022-02-07 15:59 UTC, aktiur approved these changes

2022-02-07 15:59 UTC, merged